Repository AshuKulu/HacktoberFest2021, pull requests merged in 2020-10, with the labels that each got.

#13 Bubble_sort.cpp
  Bubble_sort.cpp
Labels: hactoberfest-accepted

#16 added tower of hanoi program in c language
  towerofhanoi.c
Labels: good first issue

#15 Binary Search Tree
  binarySearchTree.c
Labels: hactoberfest-accepted

#22 Added BFS(Breath First Search) Code in C
  BFS.c
  mainREDBLACKTREE.c
Labels: hactoberfest-accepted

#21 created balancing equation
  balancing_equation.c
Labels: hactoberfest-accepted

#17 matrix multiplication for unknown matrix
  matrix multiplication for unknown matrix
Labels: duplicate

#59 Factors of number
  Factors.c
Labels: good first issue

#57 Create Bubble Sort using python
  Bubble_Sort_using_python.py
Labels: hactoberfest-accepted

#56 Vowel or Consonant using pointers
  Vowel or Consonant using pointers
Labels: hactoberfest-accepted

#37 Create sieve_of_eratosthenes.py
  sieve_of_eratosthenes.py
Labels: good first issue

#44 Create perfect_numbers.py
  perfect_numbers.py
Labels: hactoberfest-accepted

#49 myPage.html
  myPage.html
Labels: good first issue

#65 Added the bubble sort program in c Language
  bubblesort.c
Labels: hactoberfest-accepted

#66 Create Josephus_Problem_Circular_LL.c
  Josephus_Problem_Circular_LL.c
Labels: hactoberfest-accepted

#64 Create Count_sort.py
  Created count_Sort.py
Labels: hactoberfest-accepted

#63 Create Emi calculator.java
  Emi calculator.java
  calculatorv1.c
Labels: hactoberfest-accepted

#67 LinkedList reversal program
  reverseLinkedList.c
Labels: hactoberfest-accepted

#71 Created basic_searchnumber.py
  Reverse String.py
  basic_searchnumber.py
Labels: hactoberfest-accepted

#69 Bubble Sort using recursion in cpp
  bubble_sort_recursion.cpp
Labels: hactoberfest-accepted

#58 added towerofhanoi cpp program
  towerofHanoi.cpp
Labels: bug

#77 stack
  stack.cpp
Labels: hactoberfest-accepted
